name: tron
dependencies:
- python=3.11
- numpy
- pytorch
- qtpy
- pip
- pyqt=5.15,<6
- pip:
  - notebook
  - pandas
  - plotly
  - scipy
  - matplotlib==3.7.3
  - ipympl
  - torch_geometric
  - refl1d
